namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -44)]
		public static void Aa4434c9c_df2c_4ac8_ab49_323976fba22e() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -43)]
		public static void Ae5a0d84e_ebbc_410f_8abf_3044589a8267() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -42)]
		public static void Aea7b753f_772e_423a_9382_323ed686539a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -41)]
		public static void A30eb306b_b1c0_4675_bbac_febb5b89edf4() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -39)]
		public static void A85f3bcb3_0824_4b50_8fb2_b327356e4969() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -38)]
		public static void A709cb1da_9a56_4780_b4f7_be3a706d3225() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -37)]
		public static void A8d92a59b_9317_4e8f_b54e_1d4b6c159777() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -36)]
		public static void A0540e24e_5ac4_4407_9284_4897510577f7() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -36)]
		public static void Acc2e1702_0a4c_44b4_9c19_8ad217e25fb4() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -35)]
		public static void A60bca1e2_1154_43d7_bc0b_2031a463f939() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -34)]
		public static void A5ccb534d_8b71_4d25_a88d_f6a97b276f58() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -33)]
		public static void A2ea2e804_3242_4246_835f_e50c5929a2d3() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -32)]
		public static void A6922fff8_914a_40ce_876d_89def2eb8549() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -31)]
		public static void Aa3ee789b_7942_41df_b4c4_33e28e73a255() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -30)]
		public static void A46cdd709_4789_4294_bc12_ea92dcd7f491() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -29)]
		public static void A0013a3a4_36c9_424d_b425_65ea96a79214() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -28)]
		public static void Afec449c7_c729_492a_b1ee_0ca0616747a4() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -27)]
		public static void Abba5aad1_9fa9_4735_a684_c57b45ec9d25() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateLightmapUVs()); }

		[MenuItem("Pixyz/Toolbox/Misc/Save as .pxz", priority = 22)]
		[MenuItem("GameObject/Pixyz/Misc/Save as .pxz", priority = -3)]
		public static void A4287f234_506d_4572_abc9_a75b548e7e8a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.SaveAction()); }

	}
}